name: unit-tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize] }
  push: { branches: [main] }
  schedule:
    - cron: "0 6 * * 6"

defaults:
  run:
    shell: bash --noprofile --norc -Eeuo pipefail {0}

jobs:
  linux-unit:
    strategy:
      fail-fast: false
      matrix:
        swift-image:
          - name: swift:6.3-noble
        config:
          - mode: "debug"
          - mode: "release"

    runs-on: ubuntu-latest

    container: ${{ matrix.swift-image.name }}

    timeout-minutes: 15

    permissions:
      actions: read # For reading the previous commit's workflow runs
      contents: read

    env:
      ASAN_OPTIONS: "detect_leaks=1"

    steps:
      - name: Check out ${{ github.event.repository.name }}
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y zstd curl jq

      - name: Check relevance
        id: check-relevance
        env:
          GITHUB_TOKEN: ${{ github.token }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          SHOULD_RUN="$(.github/scripts/check-relevance.sh)"
          printf '%s\n' "should-run=${SHOULD_RUN}" >> "${GITHUB_OUTPUT}"

      - name: Restore .build
        if: ${{ steps.check-relevance.outputs.should-run == 'true' && runner.debug != '1' }}
        id: "restore-cache"
        uses: actions/cache/restore@v6
        with:
          path: .build
          key: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-${{ hashFiles('./Package.resolved') }}"
          restore-keys: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-"

      - name: Build ${{ github.event.repository.name }}
        if: ${{ steps.check-relevance.outputs.should-run == 'true' }}
        run: |
          swift build \
            --build-tests \
            --disable-xctest \
            --enable-code-coverage \
            --sanitize=address \
            --explicit-target-dependency-import-check error \
            -Xswiftc -require-explicit-sendable \
            -c ${{ matrix.config.mode }}

      - name: Cache .build
        if: ${{ steps.check-relevance.outputs.should-run == 'true' && steps.restore-cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v6
        with:
          path: .build
          key: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-${{ hashFiles('./Package.resolved') }}"

      - name: Run tests
        if: ${{ steps.check-relevance.outputs.should-run == 'true' }}
        run: |
          swift test \
            --skip "IntegrationTests." \
            --skip-build \
            --disable-xctest \
            --enable-code-coverage \
            --sanitize=address \
            -Xswiftc -require-explicit-sendable \
            -c ${{ matrix.config.mode }}

      - name: Submit code coverage
        if: ${{ steps.check-relevance.outputs.should-run == 'true' }}
        uses: vapor/swift-codecov-action@2f478f2fd22e06ca363967d0fb6c6593a8548cee # v0.3.5
        with:
          build_parameters: "-c ${{ matrix.config.mode }}"
          codecov_token: "${{ secrets.CODECOV_TOKEN }}"

  cache-swiftly-toolchain-for-macos:
    strategy:
      fail-fast: false
      matrix:
        swift:
          - version: 6.3

    runs-on: macos-26

    timeout-minutes: 20

    permissions:
      actions: read # For reading the previous commit's workflow runs
      contents: read

    env:
      SWIFTLY_HOME_DIR: "/Users/runner/.swiftly"
      SWIFTLY_BIN_DIR: "/Users/runner/.swiftly/bin"
      SWIFTLY_TOOLCHAINS_DIR: "/Users/runner/Library/Developer/Toolchains"

    steps:
      - name: Check out ${{ github.event.repository.name }}
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Update bash via Homebrew
        run: brew install bash

      - name: Check relevance
        id: check-relevance
        env:
          GITHUB_TOKEN: ${{ github.token }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          SHOULD_RUN="$(.github/scripts/check-relevance.sh)"
          printf '%s\n' "should-run=${SHOULD_RUN}" >> "${GITHUB_OUTPUT}"

      - name: Restore swiftly home
        if: ${{ steps.check-relevance.outputs.should-run == 'true' && runner.debug != '1' }}
        id: "restore-home"
        uses: actions/cache/restore@v6
        with:
          path: "${{ env.SWIFTLY_HOME_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-home-${{ matrix.swift.version }}-${{ runner.os }}"

      - name: Restore swiftly bin
        if: ${{ steps.check-relevance.outputs.should-run == 'true' && runner.debug != '1' }}
        id: "restore-bin"
        uses: actions/cache/restore@v6
        with:
          path: "${{ env.SWIFTLY_BIN_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-bin-${{ matrix.swift.version }}-${{ runner.os }}"

      - name: Restore swiftly toolchains
        if: ${{ steps.check-relevance.outputs.should-run == 'true' && runner.debug != '1' }}
        id: "restore-toolchains"
        uses: actions/cache/restore@v6
        with:
          path: "${{ env.SWIFTLY_TOOLCHAINS_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-toolchain-${{ matrix.swift.version }}-${{ runner.os }}"

      - name: Update swift via Swiftly
        if: ${{ steps.check-relevance.outputs.should-run == 'true' }}
        run: |
          # Installation commands from https://www.swift.org/install/macos
          curl -O https://download.swift.org/swiftly/darwin/swiftly.pkg
          installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
          "${SWIFTLY_BIN_DIR}/swiftly" init --assume-yes --skip-install --quiet-shell-followup
          . "${SWIFTLY_HOME_DIR}/env.sh"

          # Update GitHub PATH
          printf '%s\n' "${SWIFTLY_BIN_DIR}" >>"${GITHUB_PATH}"

          # Update swift
          swiftly install --assume-yes ${{ matrix.swift.version }}
          swiftly use --assume-yes ${{ matrix.swift.version }}

      - name: Cache swiftly home
        if: ${{ steps.check-relevance.outputs.should-run == 'true' && steps.restore-home.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v6
        with:
          path: "${{ env.SWIFTLY_HOME_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-home-${{ matrix.swift.version }}-${{ runner.os }}"

      - name: Cache swiftly bin
        if: ${{ steps.check-relevance.outputs.should-run == 'true' && steps.restore-bin.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v6
        with:
          path: "${{ env.SWIFTLY_BIN_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-bin-${{ matrix.swift.version }}-${{ runner.os }}"

      - name: Cache swiftly toolchains
        if: ${{ steps.check-relevance.outputs.should-run == 'true' && steps.restore-toolchains.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v6
        with:
          path: "${{ env.SWIFTLY_TOOLCHAINS_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-toolchain-${{ matrix.swift.version }}-${{ runner.os }}"

  macos-unit:
    strategy:
      fail-fast: false
      matrix:
        macos:
          - version: macos-15
          - version: macos-26
        xcode:
          - version: latest-stable
        swift:
          - version: 6.3
        config:
          - mode: "debug"
          - mode: "release"

    runs-on: ${{ matrix.macos.version }}

    needs: cache-swiftly-toolchain-for-macos

    timeout-minutes: 20

    permissions:
      actions: read # For reading the previous commit's workflow runs
      contents: read

    env:
      ASAN_OPTIONS: "detect_leaks=1"
      LSAN_OPTIONS: "suppressions=.github/lsan-suppressions.txt:print_suppressions=1"
      UBSAN_OPTIONS: "halt_on_error=1:print_stacktrace=1"
      SWIFTLY_HOME_DIR: "/Users/runner/.swiftly"
      SWIFTLY_BIN_DIR: "/Users/runner/.swiftly/bin"
      SWIFTLY_TOOLCHAINS_DIR: "/Users/runner/Library/Developer/Toolchains"

    steps:
      - name: Check out ${{ github.event.repository.name }}
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Update bash via Homebrew
        run: brew install bash

      - name: Check relevance
        id: check-relevance
        env:
          GITHUB_TOKEN: ${{ github.token }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          SHOULD_RUN="$(.github/scripts/check-relevance.sh)"
          printf '%s\n' "should-run=${SHOULD_RUN}" >> "${GITHUB_OUTPUT}"

      - name: Setup appropriate Xcode version
        if: ${{ steps.check-relevance.outputs.should-run == 'true' }}
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ matrix.xcode.version }}

      - name: Restore swiftly home
        if: ${{ steps.check-relevance.outputs.should-run == 'true' }}
        id: "restore-home"
        uses: actions/cache/restore@v6
        with:
          path: "${{ env.SWIFTLY_HOME_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-home-${{ matrix.swift.version }}-${{ runner.os }}"

      - name: Restore swiftly bin
        if: ${{ steps.check-relevance.outputs.should-run == 'true' }}
        id: "restore-bin"
        uses: actions/cache/restore@v6
        with:
          path: "${{ env.SWIFTLY_BIN_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-bin-${{ matrix.swift.version }}-${{ runner.os }}"

      - name: Restore swiftly toolchains
        if: ${{ steps.check-relevance.outputs.should-run == 'true' }}
        id: "restore-toolchains"
        uses: actions/cache/restore@v6
        with:
          path: "${{ env.SWIFTLY_TOOLCHAINS_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-toolchain-${{ matrix.swift.version }}-${{ runner.os }}"

      - name: Update swift via Swiftly
        if: ${{ steps.check-relevance.outputs.should-run == 'true' }}
        run: |
          # Workaround some kind of GitHub caching issue where it struggles to restore or cache the swiftly toolchain
          BLOCK_SIZE="$(du -s '${{ env.SWIFTLY_TOOLCHAINS_DIR }}' | awk '{print $1}')"
          if [[ "${BLOCK_SIZE}" -lt 1024 ]]; then
            printf '%s\n' "Toolchain directory is too small (${BLOCK_SIZE} blocks), deleting all swiftly directories for fresh installation"
            rm -rf '${{ env.SWIFTLY_TOOLCHAINS_DIR }}' '${{ env.SWIFTLY_BIN_DIR }}' '${{ env.SWIFTLY_HOME_DIR }}'
          else
            printf '%s\n' "Toolchain directory is large enough (${BLOCK_SIZE} blocks), will use the restored toolchain"
          fi

          # Installation commands from https://www.swift.org/install/macos
          curl -O https://download.swift.org/swiftly/darwin/swiftly.pkg
          installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
          "${SWIFTLY_BIN_DIR}/swiftly" init --assume-yes --skip-install --quiet-shell-followup
          . "${SWIFTLY_HOME_DIR}/env.sh"

          # Update GitHub PATH
          printf '%s\n' "${SWIFTLY_BIN_DIR}" >>"${GITHUB_PATH}"

          # Update swift
          swiftly install --assume-yes ${{ matrix.swift.version }}
          swiftly use --assume-yes ${{ matrix.swift.version }}

      - name: Restore .build
        if: ${{ steps.check-relevance.outputs.should-run == 'true' && runner.debug != '1' }}
        id: "restore-cache"
        uses: actions/cache/restore@v6
        with:
          path: .build
          key: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift.version }}-${{ matrix.macos.version }}-${{ hashFiles('./Package.resolved') }}"
          restore-keys: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift.version }}-${{ matrix.macos.version }}-"

      - name: Build ${{ github.event.repository.name }}
        if: ${{ steps.check-relevance.outputs.should-run == 'true' }}
        run: |
          swift build \
            --build-tests \
            --disable-xctest \
            --enable-code-coverage \
            --sanitize=address --sanitize=undefined \
            --explicit-target-dependency-import-check error \
            -Xswiftc -require-explicit-sendable \
            -c ${{ matrix.config.mode }}

      - name: Cache .build
        if: ${{ steps.check-relevance.outputs.should-run == 'true' && steps.restore-cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v6
        with:
          path: .build
          key: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift.version }}-${{ matrix.macos.version }}-${{ hashFiles('./Package.resolved') }}"

      - name: Run tests
        if: ${{ steps.check-relevance.outputs.should-run == 'true' }}
        run: |
          swift test \
            --skip "IntegrationTests." \
            --skip-build \
            --disable-xctest \
            --enable-code-coverage \
            --sanitize=address --sanitize=undefined \
            -Xswiftc -require-explicit-sendable \
            -c ${{ matrix.config.mode }}

      - name: Submit code coverage
        if: ${{ steps.check-relevance.outputs.should-run == 'true' }}
        uses: vapor/swift-codecov-action@2f478f2fd22e06ca363967d0fb6c6593a8548cee # v0.3.5
        with:
          build_parameters: "-c ${{ matrix.config.mode }}"
          codecov_token: "${{ secrets.CODECOV_TOKEN }}"
